Update cross-compile-gnss-sdr.yml

diff --git a/.github/workflows/cross-compile-gnss-sdr.yml b/.github/workflows/cross-compile-gnss-sdr.yml
--- a/.github/workflows/cross-compile-gnss-sdr.yml
+++ b/.github/workflows/cross-compile-gnss-sdr.yml
@@ -23,7 +23,28 @@ jobs:
           . ~/raspberrypi-sdk/environment-setup-cortexa76-geniux-linux
           env|grep -e "^LD" -e "^CC" -e "^AR"
           cd gnss-sdr
-          cmake -S . -B build -DCMAKE_TOOLCHAIN_FILE=cmake/Toolchains/oe-sdk_cross.cmake -DCMAKE_INSTALL_PREFIX=/usr -DENABLE_SYSTEM_TESTING=ON
+
+          max_retries=5
+          retry_delay=1
+          
+          for attempt in $(seq 1 "$max_retries"); do
+              echo "Attempt $attempt of $max_retries..."
+              
+              if  cmake -S . -B build -DCMAKE_TOOLCHAIN_FILE=cmake/Toolchains/oe-sdk_cross.cmake -DCMAKE_INSTALL_PREFIX=/usr -DENABLE_SYSTEM_TESTING=ON -DENABLE_SYSTEM_TESTING_EXTRA=ON; then
+                  echo "Cmake configure succeeded on attempt $attempt."
+                  break  # Exit the loop on success
+              else
+                  echo "Command failed on attempt $attempt."
+                  if [ "$attempt" -lt "$max_retries" ]; then
+                      echo "Retrying in $retry_delay seconds..."
+                      sleep "$retry_delay"
+                  else
+                      echo "cmake configure failed after $max_retries attempts."
+                      exit 1  # Exit the script with an error if all retries fail
+                  fi
+              fi
+          done
+         
           cmake --build build -j
           sshfs root@10.1.3.134:/ /mnt/sdimage2
           cmake --install build/ --prefix /mnt/sdimage2/
