Update gnss-sdr-tests.yml

diff --git a/.github/workflows/gnss-sdr-tests.yml b/.github/workflows/gnss-sdr-tests.yml
--- a/.github/workflows/gnss-sdr-tests.yml
+++ b/.github/workflows/gnss-sdr-tests.yml
@@ -18,41 +18,41 @@ jobs:
           
       - name: Test gnss-sdr in the Raspberrypi 5
         run: |
-            ssh root@10.1.3.134 gnss-sdr-tests/run_tests --gtest_color=no --gtest_output=json --gtest_filter="ReedSolomonE1BTest*"
-            rsync -av root@10.1.3.134:/home/root/gnss-sdr-tests/test_detail.json /home/xavier/actions-runner/_work/gnss-sdr/gnss-sdr/gnss-sdr/
+            ssh root@10.1.3.134 gnss-sdr-tests/run_tests --gtest_color=no --gtest_output=xml --gtest_filter="ReedSolomonE1BTest*"
+            rsync -av root@10.1.3.134:/home/root/gnss-sdr-tests/test_detail.xml /home/xavier/actions-runner/_work/gnss-sdr/gnss-sdr/gnss-sdr/
 
-      - name: Parse and Display Test Results
-        run: |
-          pwd
-          ls -las
-          # Parse the JSON
-          suite=$(jq -r '.testsuites[].name' test_detail.json)
-          total=$(jq -r '.tests' test_detail.json)
-          passed=$(jq -r '[.testsuites[].testsuite[] | select(.result == "COMPLETED")]|length' test_detail.json)
-          failed=$(jq -r '.testsuites[].failures' test_detail.json)
-          errors=$(jq -r '.testsuites[].errors' test_detail.json)
+      #- name: Parse and Display Test Results
+      #  run: |
+      #    pwd
+      #    ls -las
+      #    # Parse the JSON
+      #    suite=$(jq -r '.testsuites[].name' test_detail.json)
+      #    total=$(jq -r '.tests' test_detail.json)
+      #    passed=$(jq -r '[.testsuites[].testsuite[] | select(.result == "COMPLETED")]|length' test_detail.json)
+      #    failed=$(jq -r '.testsuites[].failures' test_detail.json)
+      #    errors=$(jq -r '.testsuites[].errors' test_detail.json)
 
-          echo "Test Suite: $suite"
-          echo "Total Tests: $total"
-          echo "Passed: $passed"
-          echo "Failed: $failed"
+      #   echo "Test Suite: $suite"
+      #   echo "Total Tests: $total"
+      #   echo "Passed: $passed"
+      #   echo "Failed: $failed"
 
-          if [ "$failed" -gt 0 ]; then
-            echo "Error Details:"
-            echo "$errors" | jq -r '.[] | "Test: \(.test), Message: \(.message)"'
-          fi
+      #    if [ "$failed" -gt 0 ]; then
+      #      echo "Error Details:"
+      #      echo "$errors" | jq -r '.[] | "Test: \(.test), Message: \(.message)"'
+      #    fi
 
       - name: Publish Test Results
         uses: EnricoMi/publish-unit-test-result-action/linux@v2
         if: always()
         with:
           files: |
-            test_detail.json
+            test_detail.xml
       
-      - name: Upload Test Report
-        uses: dorny/test-reporter@v1
-        if: success() || failure() 
-        with:
-          name: Test Results
-          path: /home/xavier/actions-runner/_work/gnss-sdr/gnss-sdr/gnss-sdr/test_detail.json
-          reporter: dart-json
+      #- name: Upload Test Report
+      #  uses: dorny/test-reporter@v1
+      #  if: success() || failure() 
+      #  with:
+      #    name: Test Results
+      #    path: /home/xavier/actions-runner/_work/gnss-sdr/gnss-sdr/gnss-sdr/test_detail.json
+      #    reporter: dart-json
